app/mod_movie/models.py
from app import cache, db

class Movie(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    title = db.Column(db.String(50), nullable=False)
    description = db.Column(db.String(255), nullable=True)
    # image = db.Column(db.String(100), nullable=False, server_default='')

    @staticmethod
    @cache.memoize(timeout=50)
    def get_all_movies():
        # import pdb; pdb.set_trace()
        return Movie.query.all()

app/mod_user/models.py
from app import db
from flask_user import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)

    # User authentication information
    username = db.Column(db.String(50), nullable=False, unique=True)
    password = db.Column(db.String(255), nullable=False, server_default='')
    reset_password_token = db.Column(db.String(100), nullable=False, server_default='')

    # User email information
    email = db.Column(db.String(255), nullable=False, unique=True)
    confirmed_at = db.Column(db.DateTime())

    # User information
    is_enabled = db.Column(db.Boolean(), nullable=False, default=False)
    active = db.Column('is_active', db.Boolean(), nullable=False, server_default='0')
    first_name = db.Column(db.String(100), nullable=False, server_default='')
    last_name = db.Column(db.String(100), nullable=False, server_default='')

    roles = db.relationship('Role', secondary='user_roles',
            backref=db.backref('users', lazy='dynamic'))

# Define Role model
class Role(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), unique=True)

# Define UserRoles model
class UserRoles(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id', ondelete='CASCADE'))
    role_id = db.Column(db.Integer(), db.ForeignKey('role.id', ondelete='CASCADE'))


# class User(db.Model, UserMixin):
#     id = db.Column(db.Integer, primary_key=True)
# 
#     # User Authentication information
#     # username = db.Column(db.String(50), nullable=False, unique=True)
# 
#     # User Email information
#     email = db.Column(db.String(255), nullable=False, unique=True)
# 
#     # User information
#     first_name = db.Column(db.String(50), nullable=True, default='')
#     last_name = db.Column(db.String(50), nullable=True, default='')
# 
#     def is_admin(self):
#         return True
# 
#     def __str__(self):
#         return self.email

app/__init__.py
import os

from flask import Flask, render_template, request
from flask.ext.admin import Admin
from flask.ext.cache import Cache
from flask.ext.sqlalchemy import SQLAlchemy
from flask_user import UserManager, SQLAlchemyAdapter

# from settings import DevConfig as config

app = Flask(
    __name__,
    # template_folder=config.TEMPLATE_DIR,
)
app.config.from_object(os.environ['APP_SETTINGS'])
db = SQLAlchemy(app)
admin = Admin(app)
cache = Cache(app,config={'CACHE_TYPE': 'simple'})

from app.mod_site.controllers import mod_site
app.register_blueprint(mod_site)

from app.mod_user.controllers import mod_user
app.register_blueprint(mod_user)

from app.mod_movie.controllers import mod_movie
app.register_blueprint(mod_movie)

from app.mod_user.models import User
db_adapter = SQLAlchemyAdapter(db, User)
user_manager = UserManager(db_adapter, app)

@app.errorhandler(404)
def not_found_error(error):
    return render_template('404.html'), 404

from app.mod_admin import init_admin
init_admin(admin)

app/mod_admin/__init__.py
from flask.ext.admin import Admin, BaseView, expose
from flask.ext.admin.contrib.sqla import ModelView
from flask_user import current_user

from app import db
from app.mod_user.models import User
from app.mod_movie.models import Movie

class MyView(BaseView):
    def is_accessible(self):
        # return current_user.is_admin()
        return True

    @expose('/')
    def index(self):
        return self.render('admin/index.html')

class MyModelView(ModelView):
    column_display_pk = True

    def is_accessible(self):
        # import pdb; pdb.set_trace()
        return True
        # if not current_user.is_authenticated: return False
        # return current_user.has_roles('admin')

def init_admin(_admin):
    _admin.add_view(MyView(name='Hello'))
    _admin.add_view(MyModelView(User, db.session, endpoint='admin_user'))
    _admin.add_view(MyModelView(Movie, db.session, endpoint='admin_movie'))

app/mod_movie/controllers.py
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for
from flask.ext.user.signals import user_logged_in, user_registered
from flask_user import current_user, login_required

import app

from app import cache, db
from models import Movie

mod_movie = Blueprint('movie', __name__, url_prefix='/movie')


@mod_movie.route('/recommendation')
def recommendation():
    movies = Movie.get_all_movies()
    return render_template("movie/recommendation.html", movies=movies)

@cache.cached(timeout=50)
@mod_movie.route('/<int:id>')
def index(id):
    # import pdb; pdb.set_trace()
    # id = request.args.get('id')
    movie = Movie.query.get(id)
    return render_template("movie/recommendation.html", movies=[movie])

app/mod_site/controllers.py
import os

from flask import Blueprint, request, render_template
from flask_user import current_user, login_required
from werkzeug import secure_filename

from app import app
from app.mod_movie.models import Movie

mod_site = Blueprint('site', __name__, url_prefix='/')

@mod_site.route('/', methods=['GET'])
def index():
    movies =  Movie.get_all_movies()
    m = movies[0]
    # import pdb; pdb.set_trace()
    return render_template("site/index.html", movies=movies)

app/mod_user/controllers.py
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for
from flask.ext.user.signals import user_logged_in, user_registered
from flask_user import current_user, login_required

import app

from app import db
from models import User

mod_user = Blueprint('user', __name__, url_prefix='/user')

@mod_user.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    form = UserForm()
    if form.validate_on_submit():
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        db.session.commit()
        flash('Setting saved.')
        return redirect(url_for('.dashboard'))
    form.first_name.data = current_user.first_name
    form.last_name.data = current_user.last_name
    form.phone.data = current_user.phone
    form.address.data = current_user.address
    form.city.data = City.get_name_by_id(current_user.city_id)
    form.country_id.data = Country.get_name_by_id(
        current_user.country_id)
    form.zipcode.data = current_user.zipcode
    return render_template("user/dashboard.html", form=form)

@mod_user.route('/update', methods=['POST'])
@login_required
def update_user():
    form = UserForm()
    if form.validate_on_submit():
        print form
    return 'hi'

@mod_user.route('/')
def show_users():
    users = User.query.all()
    return render_template("user/index.html", users=users)

@mod_user.route('/profile')
@login_required
def user_profile():
    return 'hi'

@mod_user.route('/setting')
@login_required
def setting():
    return 'setting'

# seems the hook doesn't work if placed here
@user_logged_in.connect_via(app)
def _after_login_hook(sender, user, **extra):
    sender.logger.info('user logged in')
    print 'mod_user controller: user logged in'

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">数问</a>
            {% if current_user.is_authenticated %}
            {% else %}
          <a class="navbar-brand" href="{{url_for('user.login')}}">登录</a>
            {% endif %}
          <a class="navbar-brand" href="{{url_for('movie.recommendation')}}">推荐电影</a>
          <a class="navbar-brand" href="{{url_for('user.setting')}}">设置</a>
          <a class="navbar-brand" href="{{url_for('admin.index')}}">管理员</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            {% if current_user.is_authenticated %}
          <form class="navbar-form navbar-right">
                <a href={{url_for('user.logout')}} class="btn btn-success">登出</a>
          </form>
            {% else %}
          {% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
          <form class="navbar-form navbar-right" method="POST" action="{{url_for('user.login')}}" role="form">
            {% if form %}
            {{ form.hidden_tag() }}
            {% else %}
            no form!
            {% endif %}
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control" name="username" id="username">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control" name="password" id="password">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
            {% endif %}
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>机器学习推荐系统</h1>
        <p>推荐引擎的出现，使用户获取信息的方式从简单的目标明确的数据的搜索转换到更高级更符合人们使用习惯的上下文信息更丰富的信息发现。</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">了解更多 &raquo;</a></p>
      </div>
    </div>

    <div id="main-div">
        {% block content %}
        {% endblock %}
    </div>


      <hr>

      <div class="footer">
        <p>&copy; 2015 数问 Inc.</p>
      </div>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/templates/movie/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

<div class="row">
<div class="col-md-6">
    <ul>
    {% for user in users %}
    <li> <a href="/user/"{{user.email}}>{{user.email}}</a>, {{user.first_name}}, {{user.last_name}}
    {% endfor %}
    </ul>
</div>
</div>

</div>

{% endblock %}

app/templates/movie/recommendation.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

<div class="row">
    {% for movie in movies %}
        <div class="col-md-4">
            <h2>{{movie.title}}</h2><p>{{movie.description}}</p>
            <p><a class="btn btn-default" href="/movie/{{movie.id}}" role="button">观看 &raquo;</a></p>
        </div>
    {% endfor %}
</div>

</div>

{% endblock %}

app/templates/site/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container"> 

<div class="row">
    {% for movie in movies %}
    <div class="col-md-4">
          <h2>{{movie.title}}</h2>
          <p>{{movie.description}}</p>
          <p><a class="btn btn-default" href="/movie/{{movie.id}}" role="button">观看 &raquo;</a></p>
    </div>
    {% endfor %}
</div>

</div>

{% endblock %}

app/templates/user/login.html
{% extends 'base.html' %}


{% block content %}

<section id="form">
    <div class="container">
        <div class="row">
            <div class="col-sm-7 col-md-6 col-lg-5 col-centered">


                {% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
                <h2>{%trans%}登录{%endtrans%}</h2>
                <h3>user1@example.com: Password1</h3>
                <form action="" method="POST" class="form" role="form">
                    {{ form.hidden_tag() }}

                    {# Username or Email field #}
                    {% set field = form.username if user_manager.enable_username else form.email %}
                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                        {# Label on left, "New here? Register." on right #}
                        <div class="row">
                            <div class="col-xs-6">
                                <label for="{{ field.id }}" class="control-label">{{ field.label.text }}</label>
                            </div>
                            <div class="col-xs-6 text-right">
                                {% if user_manager.enable_register and not user_manager.require_invitation %}
                                    <a href="{{ url_for('user.register') }}" tabindex='190'>
                                        {%trans%}New here? Register.{%endtrans%}</a>
                                {% endif %}
                            </div>
                        </div>
                        {{ field(class_='form-control', tabindex=110) }}
                        {% if field.errors %}
                            {% for e in field.errors %}
                                <p class="help-block">{{ e }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>

                    {# Password field #}
                    {% set field = form.password %}
                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                        {# Label on left, "Forgot your Password?" on right #}
                        <div class="row">
                            <div class="col-xs-6">
                                <label for="{{ field.id }}" class="control-label">{{ field.label.text }}</label>
                            </div>
                            <div class="col-xs-6 text-right">
                                {% if user_manager.enable_forgot_password %}
                                    <a href="{{ url_for('user.forgot_password') }}" tabindex='195'>
                                        {%trans%}Forgot your Password?{%endtrans%}</a>
                                {% endif %}
                            </div>
                        </div>
                        {{ field(class_='form-control', tabindex=120) }}
                        {% if field.errors %}
                            {% for e in field.errors %}
                                <p class="help-block">{{ e }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>

                    {# Remember me #}
                    {% if user_manager.enable_remember_me %}
                    {{ render_checkbox_field(login_form.remember_me, tabindex=130) }}
                    {% endif %}

                    {# Submit button #}
                    {{ render_submit_field(form.submit, tabindex=180) }}
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}